name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 18, 20, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: Europe/Paris
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: System info
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "yarn"
          yarn -v
      - name: Install modules
        run: yarn install
      - name: Run lint task
        run: yarn lint
      - name: Run tests
        run: yarn test
