name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 16, 18, 20 ]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: System info
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "yarn"
          yarn -v
      - name: Install modules
        run: yarn
      - name: Run lint tasks
        run: yarn lint
      - name: Run tests
        run: yarn test
